from .internal import (
    PC_IMPERSONATE,
    PC_DATA_HEADERS,
    PC_PAGE_HEADERS,
    TIMEOUT,
    RETRY,
    APP_IMPERSONATE,
    APP_DATA_HEADERS,
    FILE_SIGNATURES,
    FILE_SIGNATURES_LENGTH,
)
