from .internal import (
    PC_USERAGENT,
    PC_DATA_HEADERS,
    PC_PAGE_HEADERS,
    PC_DOWNLOAD_HEADERS,
    TIMEOUT,
    RETRY,
    APP_USERAGENT,
    APP_DATA_HEADERS,
    APP_HEADERS,
    APP_DOWNLOAD_HEADERS,
    FILE_SIGNATURES,
    FILE_SIGNATURES_LENGTH,
)
